# Generated by Django 4.1.1 on 2022-12-29 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.TextField(max_length=50)),
                ('telefono', models.TextField(verbose_name=15)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactos.grupo')),
            ],
        ),
    ]
