# Generated by Django 4.1.1 on 2022-12-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='observacion',
            field=models.TextField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
