# Generated by Django 4.1.1 on 2022-12-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0002_contacto_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.TextField(max_length=15),
        ),
    ]
