# Generated by Django 4.1.1 on 2022-12-29 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0005_alter_contacto_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contactos.grupo'),
        ),
    ]
