# Generated by Django 4.1.1 on 2022-12-29 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0006_alter_contacto_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='observacion',
        ),
        migrations.AddField(
            model_name='contacto',
            name='apellido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='celular',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacto',
            name='compañia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='contacto',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
