# Generated by Django 4.1.1 on 2022-12-30 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0007_remove_contacto_direccion_remove_contacto_grupo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contactos.grupo'),
        ),
    ]
